<main>
    
    <h1>Page d'accueil</h1>
    
   
   <?php 
   foreach($tableCategories as $category) {?>
    <article>
        <h2><?= $category["categoryTitle"]  ?></h2>
        <section>
            <h3><?= $category[0]['title']?></h3>
            <p><?= $category[0]['excerpt']?></p>
        </section>
        <section>
            <h3><?= $category[1]['title']?></h3>
            <p><?= $category[0]['excerpt']?></p>
        </section>
    </article>
    <?php }?>

    
</main>