<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					
						<?php if(empty($_SESSION)) {?>
						<li>
						<a href="index.php?route=connexion">Connexion</a>
						</li>
						<?php } ?>
					
					
					<li>
						<a href="index.php?route=inscription">Inscription</a>
					</li>
					<li>
						<a href="index.php?route=espace-perso">Espace Perso</a>
					</li>
					
				</ul>
			</nav>
		</header>
		<?php
			if($route === "connexion")
			{
			    
			    require 'templates/connexion.phtml';
			    
			    
			}
			elseif($route === "home")
			{
				
				require 'templates/home.phtml';
			}
			
			elseif($route === "inscription")
			{
			    
			    require 'templates/inscription.phtml';
			}
			elseif($route === "espace-perso")
			{
			    
			    require 'templates/espace-perso.phtml';
			    
			}
			elseif($route === 'checkUser')
			{
				require 'templates/checkUser.phtml';
			}
			elseif($route === 'checkpost')
			{
				
				require 'templates/checkpost.phtml';
			}
			
			elseif($route === "existepas")
			{
			    require 'templates/existepas.phtml';
			    
			}
			elseif($route === 'categories')
			{
				
				require 'templates/categories.phtml';
			}
			elseif($route === 'category')
			{
				
				require 'templates/category.phtml';
			}
			
		?>
	</body>
</html>